version: '2.1'

services:
  base-app:
    build:
      context: .
      args: 
        NODE_ENV: ${NODE_ENV-production}
    environment:
      NODE_ENV: ${NODE_ENV-production}

  app:
    extends:
      service: base-app
    ports:
      - 3000:3000
  dev-app:
    extends:
      service: base-app
    ports:
      - 3000:3000

volumes:
  node_modules:
